version: '3.8'
services:
  cis380:
    build: .
    image: cis380/docker-env
    environment:
      - TERM=xterm-256color
    volumes:
      - ${CIS380_PROJECT_HOME:?variable empty or unset}:/home/cis380
